// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn0-gJcr4sXqsEQWuhocqFhqXFZcLXxPs',
    appId: '1:582398179476:web:bbee8154912fa91cac1c81',
    messagingSenderId: '582398179476',
    projectId: 'todolist-cc',
    authDomain: 'todolist-cc.firebaseapp.com',
    storageBucket: 'todolist-cc.appspot.com',
    measurementId: 'G-FLY23LD88E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacmMwY96cIjzqXWahBIOsOKrTpkzPjpk',
    appId: '1:582398179476:android:d5b46e17d0f5401fac1c81',
    messagingSenderId: '582398179476',
    projectId: 'todolist-cc',
    storageBucket: 'todolist-cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcBmIVy9-CaGLDBCMO3Uq72mWmHd-VOo',
    appId: '1:582398179476:ios:f2dc3edaf4912a67ac1c81',
    messagingSenderId: '582398179476',
    projectId: 'todolist-cc',
    storageBucket: 'todolist-cc.appspot.com',
    iosClientId: '582398179476-oga3tgt4pctvufeomauoa58ll2kt6fss.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistCc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcBmIVy9-CaGLDBCMO3Uq72mWmHd-VOo',
    appId: '1:582398179476:ios:f2dc3edaf4912a67ac1c81',
    messagingSenderId: '582398179476',
    projectId: 'todolist-cc',
    storageBucket: 'todolist-cc.appspot.com',
    iosClientId: '582398179476-oga3tgt4pctvufeomauoa58ll2kt6fss.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistCc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0-gJcr4sXqsEQWuhocqFhqXFZcLXxPs',
    appId: '1:582398179476:web:11f290696678f9a6ac1c81',
    messagingSenderId: '582398179476',
    projectId: 'todolist-cc',
    authDomain: 'todolist-cc.firebaseapp.com',
    storageBucket: 'todolist-cc.appspot.com',
    measurementId: 'G-2GJEBJ0RS5',
  );

}